name: AoC 2022 Rust

on:
  push:
  pull_request:
    branches: [ develop, master ]

env:
  CARGO_TERM_COLOR: always

jobs:

  aoc_17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
          override: true
          components: rustfmt, clippy

    - name: Build
      run: cargo build
      working-directory: aoc_17
    - name: Run
      run: cargo run -- src/input.txt
      working-directory: aoc_17
